"""add config plane tables

Revision ID: d6524197e854
Revises: a31d238267a4
Create Date: 2026-07-20 08:01:45.732979
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6524197e854'
down_revision: Union[str, None] = 'a31d238267a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_scopes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cidrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hosts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exclusions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='scopestatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factory_reset_logs',
    sa.Column('initiated_by', sa.String(length=255), nullable=False),
    sa.Column('reset_type', sa.Enum('full', 'data_only', name='resettype'), nullable=False),
    sa.Column('attestation_hash', sa.String(length=255), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practitioner_licenses',
    sa.Column('license_key', sa.String(length=255), nullable=False),
    sa.Column('operator_name', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.Enum('self_assessment', 'practitioner', name='licensetier'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'expired', name='licensestatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_key')
    )
    op.create_table('token_enrollments',
    sa.Column('token_serial', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.Enum('yubikey', 'encrypted_usb', 'software_dev', name='tokentype'), nullable=False),
    sa.Column('enrolled_by', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'revoked', name='tokenstatus'), nullable=False),
    sa.Column('public_key_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_serial')
    )
    op.create_table('config_plane_sessions',
    sa.Column('token_id', sa.Uuid(), nullable=False),
    sa.Column('operator', sa.String(length=255), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'closed', 'force_closed', name='sessionstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['token_enrollments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_change_logs',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('operator', sa.String(length=255), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('diff_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifact_type', sa.String(length=255), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['config_plane_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config_change_logs')
    op.drop_table('config_plane_sessions')
    op.drop_table('token_enrollments')
    op.drop_table('practitioner_licenses')
    op.drop_table('factory_reset_logs')
    op.drop_table('assessment_scopes')
    # ### end Alembic commands ###
